# Generated by Django 5.0.6 on 2024-05-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bookedseat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrubuter', models.CharField(max_length=30)),
                ('movie_name', models.CharField(max_length=30)),
                ('actor_name', models.CharField(max_length=30)),
                ('ticket_price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
