# Generated by Django 5.0.6 on 2024-05-29 02:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_slot_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='poster',
            field=models.ImageField(default='placeholder.jpg', upload_to='poster'),
        ),
        migrations.AddField(
            model_name='slot_register',
            name='poster',
            field=models.ImageField(default='placeholder.jpg', upload_to='poster'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='slot_register',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
