# Generated by Django 5.0.6 on 2024-05-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_book_poster_slot_register_poster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='poster',
            field=models.ImageField(default='', upload_to='images/posters'),
        ),
        migrations.AlterField(
            model_name='slot_register',
            name='poster',
            field=models.ImageField(default='', upload_to='images/posters'),
        ),
    ]
