# Generated by Django 5.0.6 on 2024-05-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_book_poster_alter_slot_register_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedseat',
            name='id',
        ),
        migrations.AlterField(
            model_name='bookedseat',
            name='seat_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
