# Generated by Django 5.0.6 on 2024-05-29 11:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_book_actor_name_alter_book_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='actor_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='book',
            name='movie_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='ticket_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bookedseat',
            name='seat_number',
            field=models.CharField(max_length=10),
        ),
    ]
