# Generated by Django 5.0.6 on 2024-05-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_bookedseat_id_alter_book_actor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedseat',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
