# Generated by Django 5.0.6 on 2024-05-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_bookedseat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedseat',
            name='seat_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
