# Generated by Django 5.0.6 on 2024-05-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_show_alter_bookedseat_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='add description please'),
        ),
        migrations.AddField(
            model_name='slot_register',
            name='description',
            field=models.TextField(default='add description please'),
        ),
    ]
