# Generated by Django 5.0.6 on 2024-05-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_book_id_remove_slot_register_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='screen_no',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='slot_register',
            name='screen_no',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
