# Generated by Django 5.0.6 on 2024-05-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_book_id_slot_register_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedseat',
            name='time_of_booking',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
