# Generated by Django 5.0.6 on 2024-05-30 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_bookedseat_time_show_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedseat',
            old_name='time_of_booking',
            new_name='time',
        ),
    ]
