# Generated by Django 5.0.6 on 2024-05-30 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_time_of_booking_bookedseat_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedseat',
            name='time',
        ),
    ]
