# Generated by Django 5.0.6 on 2024-05-31 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_days_show_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_time', models.TimeField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='days',
            name='day',
            field=models.DateField(default=True, null=True),
        ),
    ]
