# Generated by Django 5.0.6 on 2024-05-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_days_cinema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot_register',
            name='poster',
            field=models.ImageField(default='', upload_to='poster'),
        ),
    ]
