# Generated by Django 5.0.6 on 2024-06-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_book_poster_alter_slot_register_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedseat',
            name='total_seats',
            field=models.IntegerField(default=70),
        ),
    ]
